name: Release new version of addon to WoW Interface

on:
  workflow_dispatch:
    # Enables a button to manually run this against the main branch
    branches: [ main ]
  push:
    # Enables automatic deploys off pushes/merges into the main branch
    branches: [ main ]

jobs:
  build:
    uses: icbat/wow-addon-github-workflow/.github/workflows/release-wowi.yml@main
    with:
      addon_name: VendorOldGear
      addon_bundled_files: VendorOldGear.lua LICENSE README.md libs/ embed.xml
      wowi_id: 26187
    secrets:
      wowi_api_token: ${{secrets.WOWI_API_TOKEN}}
